sudo: required
dist: trusty
addons:
  apt:
    packages:
    - php5-mysql

language: node_js
node_js: 6

os:
  - linux

services:
  - docker 

before_install:
  - sudo docker run -d -p 3306:3306 mysql:5.7
  - mysql --version
      
install:
  - yarn

script:
  - yarn travix node
  - yarn travix php

cache:
  yarn: true
  directories:
    - node_modules