sudo: required
dist: trusty

language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
  #- development

services:
  - mysql
  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - haxelib install jdbc.mysql
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  #- haxelib run travix node
  - haxelib run travix java