sudo: required
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: 'ppa:ondrej/php'
    packages:
      - mysql-server

language: node_js
node_js: 6

os:
  - linux

before_install:
  - mysql --version
      
install:
  - yarn && yarn global add switchx

script:
  - yarn travix node
  - sudo apt-get install php5.6-cli php5.6-mysql
  - yarn travix php
  - sudo apt-get install php7.1-cli php7.1-mysql && switchx install db5a1e4
  - yarn travix php

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/haxe