sudo: required
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: 'ppa:ondrej/php'
    packages:
      - mysql-server
      - php7.1-mysql

language: node_js
node_js: 6

os:
  - linux

before_install:
  - mysql --version
      
install:
  - yarn && yarn global add travlix

script:
  - travlix run --haxe 3.4.4 --target node
  - travlix run --haxe db5a1e4 --target php

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/haxe