sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    
language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
  #- development

services:
  - mysql
  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - npm install mysql
  - haxelib install jdbc.mysql
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  - haxelib run travix node
  - haxelib run travix php
  - haxelib run travix java