sudo: required
dist: trusty
addons:
  apt:
    sources:
      - mysql-5.7-trusty
      - sourceline: 'ppa:ondrej/php'
    packages:
      - mysql-server
      - php7.1
      - php7.1-cli
      - php7.1-mbstring
      - php7.1-mysql

language: node_js
node_js: 6

os:
  - linux

before_install:
  - shopt -s expand_aliases
  - alias php5.6='echo PHP 5.6'
  - mysql --version
      
install:
  - yarn

script:
  - yarn travix node
  - yarn travix php

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/haxe