sudo: required
dist: trusty
addons:
  apt:
    packages:
    - php5-mysql

language: node_js
node_js: 6

os:
  - linux

before_install:
  - sudo service mysql stop || sudo service mysql-5.6 stop || sudo stop mysql-5.6 || sudo stop mysql || echo "failed to stop mysql"
  - docker run --net=host -p 3306:3306 -d mysql:5.7
  - while ! mysqladmin ping --silent; do sleep 1; done
      
install:
  - yarn

script:
  - yarn travix node
  - yarn travix php

cache:
  yarn: true
  directories:
    - node_modules